### ISSUE TITLE
Can't use method return value in write context

### ISSUE THREAD

**Issue by jonathanheilmann** [jonathanheilmann/ext-jh_opengraphprotocol#16]
Fatal error: Can't use method return value in write context in [...]/typo3conf/ext/jh_opengraphprotocol/Classes/Service/OgRendererService.php on line 94

**Comment by bytetonight** [comment]
### Your code in lines 94 and 95 of \typo3conf\ext\jh_opengraphprotocol\Classes\Service\OgRendererService.php
if (!empty($GLOBALS['TSFE']->tmpl->getFileName($conf['image']))) {
					$og['image'][] = GeneralUtility::locationHeaderUrl($GLOBALS['TSFE']->tmpl->getFileName($conf['image']));
}               

### I replaced with the following, due to the empty() method not working on function calls apparently
$fileName = $GLOBALS['TSFE']->tmpl->getFileName($conf['image']);
 if (!empty($fileName)) {
     $og['image'][] = GeneralUtility::locationHeaderUrl($fileName);
}
